### ISSUE TITLE
[Urgent] Mixture of old and new in lab content

### ISSUE THREAD

**Issue by junichia** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator.JA-JP#8]
It is difficult to discern which exercises should be conducted. Also, the order of the labs is not in order.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Under review

**Comment by chriscarty00** [comment]
Will discuss with PM as the reviewer states labs are not in order however this is not a linguistic issue so will prod have to per referred to the writers

**Comment by stonezy123** [comment]
Now, the loc repo was updated. if still see this issue, please help open new one, because this is too old.
