### ISSUE TITLE
The "link to lab" in readme.md is an English page.

### ISSUE THREAD

**Issue by junichia** [MicrosoftLearning/SC-300-Identity-and-Access-Administrator.JA-JP#9]
The "link to lab" in readme.md is an English page.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
Looks like content on https://microsoftlearning.github.io/  is not localized - could be by design - will follow up.

**Comment by chriscarty00** [comment]
Checking with WWL PM

**Comment by stonezy123** [comment]
Now, the readme.md page updated. Closed.

**Comment by stonezy123** [comment]
https://github.com/MicrosoftLearning/SC-300-Identity-and-Access-Administrator.JA-JP/blob/OLPRODLOC/readme.md
